find_package(Git)
if(Git_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --long --dirty OUTPUT_VARIABLE __VERSION__)
  string(STRIP ${__VERSION__} __VERSION__)
  message(STATUS "${PROJECT_NAME} Library build __VERSION__ from git commit is \"${__VERSION__}\"")
endif()