package:
  name: stopeight-clibs
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  script_env:
    - CC
    - CXX

source:
  git_url: https://github.com/specpose/stopeight-clibs.git

requirements:
  build:
    - vs2019_win-64  # [win]
    - cmake >=3.4.3
    - qt >=5.6.0

about:
  summary: Comparing sequences of points in 2 dimensions.
  license_file: LICENSE
