name: "Conda Upload"

on:
  release:
    types: [created]
    branches:
      - master

jobs:
  conda-upload-ubuntu:
    name: Conda Upload Ubuntu
    runs-on: ${{ matrix.os }}
    env:
      ENV_PYTHON: '3.10'
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: 'false'
          update-conda: true
          python-version: '3.10'
      - name: Checkout submodules
        shell: bash -l {0}
        run: |
          git submodule update --init --recursive
      - name: Activate conda
        shell: bash -l {0}
        run: |
          eval "$($CONDA/condabin/conda shell.zsh hook)"
          conda activate base
      - name: Install Build requirements
        shell: bash -l {0}
        run: |
          conda install conda-build conda-verify anaconda-client
      - name: Build and Upload package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload yes
          conda build --channel specpose --token ${{ secrets.ANACONDA_TOKEN }} .


  conda-upload-mac:
    name: Conda Upload Mac
    runs-on: ${{ matrix.os }}
    env:
      ENV_PYTHON: '3.10'
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: 'false'
          update-conda: true
          python-version: '3.10'
      - name: Checkout submodules
        shell: zsh -l {0}
        run: |
          git submodule update --init --recursive
      - name: Activate conda
        shell: zsh -l {0}
        run: |
          sudo chown -R 501:20 /usr/local/miniconda
          eval "$($CONDA/condabin/conda shell.zsh hook)"
          conda activate base
      - name: Install Build requirements
        shell: zsh -l {0}
        run: |
          conda install conda-build conda-verify anaconda-client
      - name: Build and Upload package
        shell: zsh -l {0}
        run: |
          conda config --set anaconda_upload yes
          conda build --channel specpose --token ${{ secrets.ANACONDA_TOKEN }} .

  conda-upload-win:
    name: Conda Upload Windows
    runs-on: ${{ matrix.os }}
    env:
      ENV_PYTHON: '3.10'
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: 'false'
          update-conda: true
          python-version: '3.10'
      - name: Checkout submodules
        shell: powershell
        run: |
          git submodule update --init --recursive
      - name: Activate conda
        shell: powershell
        run: |
          (& $env:CONDA"\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
          conda activate base
      - name: Install Build requirements
        shell: powershell
        run: |
          conda install conda-build conda-verify anaconda-client
      - name: Build and Upload package
        shell: powershell
        run: |
          conda config --set anaconda_upload yes
          conda build --channel specpose --token ${{ secrets.ANACONDA_TOKEN }} .
